// Detect if the user is on Windows
export function isWindows(): boolean {
  if (typeof window === 'undefined') return false
  
  const userAgent = window.navigator.userAgent.toLowerCase()
  const platform = window.navigator.platform?.toLowerCase() || ''
  
  return platform.includes('win') || userAgent.includes('windows')
}

// Get country code from currency code
export function getCountryCode(currencyCode: string): string | null {
  const currencyToCountry: Record<string, string> = {
    USD: 'US',
    EUR: 'EU',
    GBP: 'GB',
    JPY: 'JP',
    CHF: 'CH',
    CAD: 'CA',
    AUD: 'AU',
    NZD: 'NZ',
    CNY: 'CN',
    HKD: 'HK',
    SGD: 'SG',
    SEK: 'SE',
    NOK: 'NO',
    DKK: 'DK',
    PLN: 'PL',
    CZK: 'CZ',
    HUF: 'HU',
    RON: 'RO',
    BGN: 'BG',
    HRK: 'HR',
    RUB: 'RU',
    TRY: 'TR',
    KRW: 'KR',
    INR: 'IN',
    BRL: 'BR',
    MXN: 'MX',
    ZAR: 'ZA',
    THB: 'TH',
    MYR: 'MY',
    PHP: 'PH',
    IDR: 'ID',
    ILS: 'IL',
    AED: 'AE',
    SAR: 'SA',
    EGP: 'EG',
    PKR: 'PK',
    CLP: 'CL',
    COP: 'CO',
    PEN: 'PE',
    ARS: 'AR',
    VND: 'VN',
    TWD: 'TW',
    ISK: 'IS',
    BAM: 'BA',
    ALL: 'AL',
    RSD: 'RS',
    MKD: 'MK',
    BYN: 'BY',
    UAH: 'UA',
    GEL: 'GE',
    AMD: 'AM',
    AZN: 'AZ',
    MDL: 'MD',
    TMT: 'TM',
    UZS: 'UZ',
    KZT: 'KZ',
    KGS: 'KG',
    TJS: 'TJ',
    BDT: 'BD',
    LKR: 'LK',
    NPR: 'NP',
    AFN: 'AF',
    MMK: 'MM',
    KHR: 'KH',
    LAK: 'LA',
    MNT: 'MN',
    BTN: 'BT',
    MVR: 'MV',
    BND: 'BN',
    MOP: 'MO',
    QAR: 'QA',
    KWD: 'KW',
    BHD: 'BH',
    OMR: 'OM',
    JOD: 'JO',
    LBP: 'LB',
    SYP: 'SY',
    YER: 'YE',
    IQD: 'IQ',
    IRR: 'IR',
    LYD: 'LY',
    TND: 'TN',
    DZD: 'DZ',
    MAD: 'MA',
    NGN: 'NG',
    GHS: 'GH',
    KES: 'KE',
    UGX: 'UG',
    TZS: 'TZ',
    ETB: 'ET',
    SDG: 'SD',
    ZMW: 'ZM',
    ZWL: 'ZW',
    BWP: 'BW',
    NAD: 'NA',
    SZL: 'SZ',
    LSL: 'LS',
    MUR: 'MU',
    SCR: 'SC',
    MWK: 'MW',
    MZN: 'MZ',
    AOA: 'AO',
    // Multi-country currencies
    XAF: 'CM', // Central African CFA Franc (Cameroon)
    XOF: 'SN', // West African CFA Franc (Senegal)
    XPF: 'PF', // CFP Franc (French Polynesia)
    XCD: 'AG', // East Caribbean Dollar (Antigua)
  }
  
  return currencyToCountry[currencyCode] || null
}